### ISSUE TITLE
No module named 'tradingbot'

### ISSUE THREAD

**Issue by ofranx** [nkaz001/sample-trading-bot#1]
I get this error when I want to run python in GitHub code I have installed other plugins

Traceback (most recent call last):
  File "/home/orhan/Belgeler/22/custom_strategy.py", line 6, in <module>
    from tradingbot.ordermanager import OrderManager
ModuleNotFoundError: No module named 'tradingbot'

**Comment by nkaz001** [comment]
Could you try like this?
`python -m tradingbot.custom_strategy`

Also, I'm still working on it and I want you to use it for just a sample and for learning.
