### ISSUE TITLE
gridbot putting sell order at loss before any buy order.

### ISSUE THREAD

**Issue by frndxyz** [nkaz001/sample-trading-bot#4]
ex. ETHUSDTPERP
1. buy order price: 1115, 0.09 eth
2. buy order price: 1110, 0.09 eth
3. sell order: 1100, 0.09 eth, current price: 1095 <- sell order at loss because there is no any buy average order executed below 1100 price yet.

also when price near buy or sell order, order get cancelled. is that any settings issue?

**Comment by nkaz001** [comment]
Could you elaborate more on the issue? I don't think having a short position first is a problem and this gridbot is intended to maintain the spread so our order will be filled only if the price moves more than the half spread within a given interval.
Basically, it's just an example for a starting point. I recommend you have to be able to write your own algo or at least fully understand what the example shows.
